In [1]:
import numpy as np
import pandas as pd
import tushare as ts
import pymysql
import datetime
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
import matplotlib
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [2]:
ts.set_token('c59597bb23c5a81d7537178e40e0307bfcb9f9b1ede382ff50623ac6')
pro = ts.pro_api()
start_dt = '20100101'
time_temp = datetime.datetime.now() - datetime.timedelta(days=1)

In [3]:
datetime.datetime.now()
datetime.timedelta(days=1)
time_temp

datetime.datetime(2019, 11, 20, 11, 33, 5, 481000)

datetime.timedelta(days=1)

datetime.datetime(2019, 11, 19, 11, 33, 5, 435000)

In [4]:
end_dt = time_temp.strftime('%Y%m%d')
end_dt

'20191119'

In [5]:
db = pymysql.connect(host='127.0.0.1', user='root', passwd='Chilugan6xiang', db='test', charset='utf8')
cursor = db.cursor()
stock_pool = ['601857.SH','002230.SZ']
total = len(stock_pool)

In [6]:
total

2

In [7]:
df = pro.daily(ts_code=stock_pool[0], start_date=start_dt, end_date=end_dt)

In [8]:
df
df.info()

ts_code trade_date   open   high    low  close  pre_close  change  \
0     601857.SH   20191119   5.50   5.54   5.49   5.54       5.52    0.02   
1     601857.SH   20191118   5.51   5.54   5.49   5.52       5.50    0.02   
2     601857.SH   20191115   5.60   5.60   5.50   5.50       5.60   -0.10   
3     601857.SH   20191114   5.57   5.62   5.56   5.60       5.57    0.03   
4     601857.SH   20191113   5.61   5.62   5.56   5.57       5.63   -0.06   
...         ...        ...    ...    ...    ...    ...        ...     ...   
2391  601857.SH   20100108  13.50  13.50  13.33  13.45      13.61   -0.16   
2392  601857.SH   20100107  13.73  13.82  13.52  13.61      13.70   -0.09   
2393  601857.SH   20100106  13.87  13.93  13.67  13.70      13.89   -0.19   
2394  601857.SH   20100105  13.69  13.96  13.60  13.89      13.63    0.26   
2395  601857.SH   20100104  13.85  13.89  13.61  13.63      13.82   -0.19   

      pct_chg        vol      amount  
0      0.3623  571970.68  315482.291  
1      0.3636  589834.71  325213.202  
2     -1.7857  803735.71  445246.533  
3      0.5386  543055.52  303823.714  
4     -1.0657  673454.95  375974.212  
...       ...        ...         ...  
2391  -1.1800  388627.03  521325.532  
2392  -0.6600  617027.89  846678.265  
2393  -1.3700  394848.00  545765.829  
2394   1.9100  567889.35  784796.660  
2395  -1.3700  337177.36  462902.705  

[2396 rows x 11 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2396 entries, 0 to 2395
Data columns (total 11 columns):
ts_code       2396 non-null object
trade_date    2396 non-null object
open          2396 non-null float64
high          2396 non-null float64
low           2396 non-null float64
close         2396 non-null float64
pre_close     2396 non-null float64
change        2396 non-null float64
pct_chg       2396 non-null float64
vol           2396 non-null float64
amount        2396 non-null float64
dtypes: float64(9), object(2)
memory usage: 206.0+ KB


In [9]:
print('Seq: ' + str(1) + ' of ' + str(total) + '   Code: ' + str(stock_pool[0]))

Seq: 1 of 2   Code: 601857.SH


In [10]:
c_len = df.shape[0]
c_len

2396

In [11]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:Chilugan6xiang@localhost:3306/test')
df.to_sql('zgsy', engine, index = False)

D:\soft\Anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 1")
  result = self._query(query)


In [12]:
import DC

In [13]:
stock = '601857.SH'
c = DC.data_collect(stock, '2016-03-01', '2017-01-01')

SELECT * FROM stock_all a where stock_code = '601857.SH' and state_dt >= '2016-03-01' and state_dt <= '2017-01-01' order by state_dt asc


ProgrammingError: (1146, "Table 'test.stock_all' doesn't exist")

In [14]:
df
df.info()

ts_code trade_date   open   high    low  close  pre_close  change  \
0     601857.SH   20191119   5.50   5.54   5.49   5.54       5.52    0.02   
1     601857.SH   20191118   5.51   5.54   5.49   5.52       5.50    0.02   
2     601857.SH   20191115   5.60   5.60   5.50   5.50       5.60   -0.10   
3     601857.SH   20191114   5.57   5.62   5.56   5.60       5.57    0.03   
4     601857.SH   20191113   5.61   5.62   5.56   5.57       5.63   -0.06   
...         ...        ...    ...    ...    ...    ...        ...     ...   
2391  601857.SH   20100108  13.50  13.50  13.33  13.45      13.61   -0.16   
2392  601857.SH   20100107  13.73  13.82  13.52  13.61      13.70   -0.09   
2393  601857.SH   20100106  13.87  13.93  13.67  13.70      13.89   -0.19   
2394  601857.SH   20100105  13.69  13.96  13.60  13.89      13.63    0.26   
2395  601857.SH   20100104  13.85  13.89  13.61  13.63      13.82   -0.19   

      pct_chg        vol      amount  
0      0.3623  571970.68  315482.291  
1      0.3636  589834.71  325213.202  
2     -1.7857  803735.71  445246.533  
3      0.5386  543055.52  303823.714  
4     -1.0657  673454.95  375974.212  
...       ...        ...         ...  
2391  -1.1800  388627.03  521325.532  
2392  -0.6600  617027.89  846678.265  
2393  -1.3700  394848.00  545765.829  
2394   1.9100  567889.35  784796.660  
2395  -1.3700  337177.36  462902.705  

[2396 rows x 11 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2396 entries, 0 to 2395
Data columns (total 11 columns):
ts_code       2396 non-null object
trade_date    2396 non-null object
open          2396 non-null float64
high          2396 non-null float64
low           2396 non-null float64
close         2396 non-null float64
pre_close     2396 non-null float64
change        2396 non-null float64
pct_chg       2396 non-null float64
vol           2396 non-null float64
amount        2396 non-null float64
dtypes: float64(9), object(2)
memory usage: 206.0+ KB


In [15]:
clo_mapping = {'trade_date':'state_dt','ts_code':'stock_code','change':'amt_change','pct_chg':'pct_change'}
df.rename(columns=clo_mapping,inplace=True)
order = ['state_dt', 'stock_code', 'open', 'close', 'high', 'low', 'vol', 'amount', 'pre_close', 'amt_change', 'pct_change']
df = df[order]
df
df.to_sql('stock_all', engine, index = False)

state_dt stock_code   open  close   high    low        vol      amount  \
0     20191119  601857.SH   5.50   5.54   5.54   5.49  571970.68  315482.291   
1     20191118  601857.SH   5.51   5.52   5.54   5.49  589834.71  325213.202   
2     20191115  601857.SH   5.60   5.50   5.60   5.50  803735.71  445246.533   
3     20191114  601857.SH   5.57   5.60   5.62   5.56  543055.52  303823.714   
4     20191113  601857.SH   5.61   5.57   5.62   5.56  673454.95  375974.212   
...        ...        ...    ...    ...    ...    ...        ...         ...   
2391  20100108  601857.SH  13.50  13.45  13.50  13.33  388627.03  521325.532   
2392  20100107  601857.SH  13.73  13.61  13.82  13.52  617027.89  846678.265   
2393  20100106  601857.SH  13.87  13.70  13.93  13.67  394848.00  545765.829   
2394  20100105  601857.SH  13.69  13.89  13.96  13.60  567889.35  784796.660   
2395  20100104  601857.SH  13.85  13.63  13.89  13.61  337177.36  462902.705   

      pre_close  amt_change  pct_change  
0          5.52        0.02      0.3623  
1          5.50        0.02      0.3636  
2          5.60       -0.10     -1.7857  
3          5.57        0.03      0.5386  
4          5.63       -0.06     -1.0657  
...         ...         ...         ...  
2391      13.61       -0.16     -1.1800  
2392      13.70       -0.09     -0.6600  
2393      13.89       -0.19     -1.3700  
2394      13.63        0.26      1.9100  
2395      13.82       -0.19     -1.3700  

[2396 rows x 11 columns]

In [34]:
import DC
stock = '601857.SH'
dc = DC.data_collect(stock, '20100301', '20191118')

SELECT * FROM stock_all a where stock_code = '601857.SH' and state_dt >= '20100301' and state_dt <= '20191118' order by state_dt asc


In [35]:
train = dc.data_train

In [36]:
train
train.dtype
train.size

array([[    12.99 ,     13.06 ,     13.09 ,     12.96 , 199447.64 ,
        259796.223],
       [    13.06 ,     12.95 ,     13.08 ,     12.9  , 193548.56 ,
        251159.316],
       [    12.95 ,     12.99 ,     13.03 ,     12.89 , 208300.1  ,
        269285.58 ],
       ...,
       [     5.61 ,      5.57 ,      5.62 ,      5.56 , 673454.95 ,
        375974.212],
       [     5.57 ,      5.6  ,      5.62 ,      5.56 , 543055.52 ,
        303823.714],
       [     5.6  ,      5.5  ,      5.6  ,      5.5  , 803735.71 ,
        445246.533]])

dtype('float64')

14154

In [37]:
target = dc.data_target
target
target.size

array([0., 1., 0., ..., 1., 0., 1.])

2359

In [38]:
test_case = [dc.test_case]

In [43]:
test_case

[array([     5.51 ,      5.52 ,      5.54 ,      5.49 , 589834.71 ,
        325213.202])]

In [45]:
from sklearn import svm
model = svm.SVC()               # 建模
model.fit(train, target)        # 训练
ans2 = model.predict(test_case) # 预测

D:\soft\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [46]:
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [47]:
ans2

array([0.])

In [49]:
ans2[0]

0.0

In [53]:
ts_code = '000001.SZ'
ts_code[:6]

'000001'